version: '3.1'

services:
  backend:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 3201:8055
    volumes:
      - ./back/uploads:/directus/uploads
      - ./back/database:/directus/database
      - ./back/extensions:/directus/extensions
    # networks:
    #   - directus
    # depends_on:
    #   - cache
    #   - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/database.sqlite3'
      # DB_HOST: 'database'
      # DB_PORT: '5432'
      DB_DATABASE: 'directus'
      # DB_USER: 'directus'
      # DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'false'

      ADMIN_EMAIL: 'lysak@lysak.com'
      ADMIN_PASSWORD: 'lysak'

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      PUBLIC_URL: 'http://localhost:3201'

  frontend:
    image: node:slim
    container_name: lystak-frontend
    restart: always
    ports:
      - 3200:3200
    volumes:
      - ./front:/usr/src/app
    working_dir: /usr/src/app
    command: "npm run dev"
    # depends_on:
    #   - backend