version: '3.1'

services:
  # backend:
  #   image: node:slim
  #   container_name: lystak-backend
  #   restart: always
  #   ports:
  #     - ${BACKEND_PORT}:8600
  #   volumes:
  #     - ./backend:/usr/src/app
  #   working_dir: /usr/src/app
  #   command: "npm run dev"

  frontend:
    image: node:slim
    container_name: lystak-frontend
    restart: always
    ports:
      - ${FRONTEND_PORT}:8500
    volumes:
      - ./front:/usr/src/app
    working_dir: /usr/src/app
    command: "npm run dev"
    # depends_on:
    #   - backend